name: Checking Runner info and Software Installations

on:
  push:
    branches:
      - main

jobs:
  check-versions:
    runs-on: utility

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display Runner Information
        run: |
          echo "OS Information:"
          uname -a
          echo "Disk Space:"
          df -h
          echo "Memory Info:"
          free -h
          echo "Hello World"

      - name: Check Software Versions
        run: |
          node -v
          npm -v
          python3 --version
          pip --version
          java --version
          mvn --version
          git --version
          docker version
          docker-compose version 
          ansible --version
          terraform --version
          packer --version
          aws --version
          kubectl version --client
          mvn --version
          trivy --version
          k9s version
          dotnet --version
          tfsec --version
          sonar-scanner --version
